In [2]:
import torch
import numpy as np

In [3]:
x = torch.empty(5, 5)
x

tensor([[4.3351e-08, 1.6997e-04, 1.0314e-08, 1.2540e+16, 2.1707e-18],
        [7.0952e+22, 1.7748e+28, 1.8176e+31, 7.2708e+31, 5.0778e+31],
        [3.2608e-12, 1.7728e+28, 7.0367e+22, 2.1715e-18, 1.3400e-08],
        [3.3856e-06, 2.1373e+20, 2.1271e+23, 7.9878e+20, 1.2973e-11],
        [5.3735e-05, 1.3400e-08, 5.2901e-08, 2.1707e-18, 7.1450e+31]])

In [4]:
x = torch.rand(5, 5)
x

tensor([[0.4604, 0.0233, 0.5278, 0.3482, 0.2400],
        [0.3619, 0.1914, 0.5839, 0.6615, 0.1465],
        [0.2711, 0.5724, 0.9730, 0.6013, 0.1160],
        [0.9451, 0.6244, 0.9921, 0.9318, 0.4490],
        [0.8649, 0.1638, 0.0423, 0.5046, 0.2163]])

In [5]:
x = torch.zeros(3, 3)

In [6]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
x = torch.tensor([[2, 3], [4, 6]])
x

tensor([[2, 3],
        [4, 6]])

In [8]:
x = x.new_ones(3, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [11]:
x = torch.rand_like(x, dtype=torch.float)

In [12]:
x

tensor([[0.4927, 0.1680, 0.7057],
        [0.4000, 0.0544, 0.3207],
        [0.2034, 0.4381, 0.5619]])

In [13]:
a = torch.rand(5, 3)
b = torch.rand(5, 3)
a
b

tensor([[0.2743, 0.4382, 0.8881],
        [0.0230, 0.1015, 0.2239],
        [0.5935, 0.3805, 0.6200],
        [0.4474, 0.8805, 0.2937],
        [0.2479, 0.3019, 0.6622]])

In [14]:
a

tensor([[0.2655, 0.4651, 0.5002],
        [0.1471, 0.9031, 0.4444],
        [0.5370, 0.1642, 0.4473],
        [0.8176, 0.0426, 0.0946],
        [0.8168, 0.2644, 0.3252]])

In [15]:
b

tensor([[0.2743, 0.4382, 0.8881],
        [0.0230, 0.1015, 0.2239],
        [0.5935, 0.3805, 0.6200],
        [0.4474, 0.8805, 0.2937],
        [0.2479, 0.3019, 0.6622]])

In [16]:
x = torch.randn(4, 4)
x

tensor([[-1.7654, -2.2687, -0.0668, -0.8355],
        [-0.5586,  0.6499,  0.9137, -0.0099],
        [-0.0486,  1.1111, -1.3160, -1.2254],
        [-1.1099, -0.8538, -0.8566, -2.5870]])

In [17]:
x = x.view(16)

In [18]:
x

tensor([-1.7654, -2.2687, -0.0668, -0.8355, -0.5586,  0.6499,  0.9137, -0.0099,
        -0.0486,  1.1111, -1.3160, -1.2254, -1.1099, -0.8538, -0.8566, -2.5870])

In [19]:
x = torch.ones(3)

In [20]:
x

tensor([1., 1., 1.])